AWSTemplateFormatVersion: '2010-09-09'
Description: "S3 Bucket Template for our CICD Pull Request"

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyCICDS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'

      Tags:
        - Key: Name
        - Value: MyCICDS3Bucket
        - Key: Environment
        - Value: "${Environment} Environment"

Outputs:
  BucketName:
    Description: "Name of created bucket"
    Value: !Ref MyCICDS3Bucket